update_fastlane

app = 'org.trustroots'
project = './ios/trustroots.xcodeproj'
workspace = './ios/trustroots.xcworkspace'
profile_uuid = 'da71a66f-0e86-42b0-8a9d-8f5af2a356f7'
scheme = 'trustroots'

default_platform(:ios)

platform :ios do
  lane :certificates do
    match(
      app_identifier: [app, 'org.trustroots'],
      type: 'development',
      clone_branch_directly: true
    )
    match(app_identifier: [app, 'org.trustroots'], type: 'appstore', clone_branch_directly: true)
  end

  private_lane :build do
    certificates

    disable_automatic_code_signing(
      path: project,
      profile_uuid: profile_uuid,
      code_sign_identity: 'iPhone Distribution',
      targets: scheme
    )

    gym(
      scheme: scheme,
      workspace: workspace,
      suppress_xcode_output: true
    )

    enable_automatic_code_signing(
      path: project,
      profile_uuid: '',
      code_sign_identity: 'iPhone Developer',
      targets: scheme
    )
  end

  lane :icon do
    appicon(
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: "./ios/trustroots/Images.xcassets",
      appicon_image_file: "./assets/icon-1024.png"
    )
  end

  lane :beta_badge do
    buildNumber = get_build_number(xcodeproj: project)
    version = get_version_number(xcodeproj: project)
    add_badge(
      shield: "v#{version}-%23#{buildNumber}-orange",
      shield_parameters: "color=rgba(235,124,64,0.9)&labelColor=rgba(100,100,100,0.8)",
      no_badge: true
    )
  end

  private_lane :bump do
    latest = latest_testflight_build_number
    if latest >= get_build_number(xcodeproj: project).to_i
      increment_build_number(xcodeproj: project, build_number: latest + 1)
      # commit_version_bump(message: ':construction_worker: iOS build version bump', xcodeproj: project)
    end
  end

  lane :test do
    build
  end

  lane :release do
    screenshots
    deliver

    bump
    icon
    build

    pilot(skip_waiting_for_build_processing: true)
  end

  lane :beta do
    bump
    icon
    beta_badge
    build

    pilot(skip_waiting_for_build_processing: true)
  end
end


platform :android do
  desc 'generate the android icons'
  lane :icon do
    android_appicon(
      appicon_image_file: 'assets/icon-1024.png',
      appicon_icon_types: [:launcher],
      appicon_path: 'android/app/src/main/res/mipmap',
      generate_rounded: true
    )
    android_appicon(
      appicon_image_file: 'assets/icon-1024.png',
      appicon_icon_types: [:notification],
      appicon_path: 'android/app/src/main/res/drawable',
      appicon_filename: 'ic_notification',
      generate_rounded: true
    )
  end

  desc 'clean and build release version'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', project_dir: 'android/', build_type: 'Release')
  end

  lane :internal do
    build
    supply(
      track: 'internal',
      track_promote_to: 'internal',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
    # git_commit(path: ['./android/gradle.properties'], message: ':construction_worker: android version bump')
    # push_to_git_remote
  end
end